default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_DATABASE'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default


test:
  <<: *default


production:
  <<: *default
